name: Update Solar Terms ICS

on:
  schedule:
    - cron: "0 0 1 1 *"  # 每年1.1执行（北京时间早上8点更新，不想再计算加一年了就这吧，需求大了再改吧）
  workflow_dispatch:      # 手动触发
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APIURL: ${{ secrets.APIURL }}
      APPKEY: ${{ secrets.APPKEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python auto_update.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ics-files/SolarTermsDateAndTime.ics
          git commit -m "Auto update Solar Terms ICS" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


